# Config file for automatic testing at travis-ci.com

language: python
os: linux
python:
- "3.8"
- "3.9-dev"
env:
- CRYPTO=2.9.1
- CRYPTO=2.9.2
- CRYPTO=3.0
- CRYPTO=3.1
- CRYPTO=3.1.1


# Command to run tests, e.g. python setup.py test
script:
  - python -m pip install --upgrade pip
  - pip install -U cryptography==$CRYPTO


